#pragma once
#include <string>
#include <vector>
struct SDL_AudioStream;

// SDL audio owns the playback clock; decoded PCM is generated by the build.
class MusicPlayer {
public:
    MusicPlayer() = default;
    MusicPlayer(const MusicPlayer&) = delete;
    MusicPlayer& operator=(const MusicPlayer&) = delete;
    ~MusicPlayer();
    bool load(const std::string& wavPath);
    bool restart();
    void release();
    bool ready() const { return mStream!=nullptr; }
    bool running() const { return mRunning; }
    float duration() const { return mDuration; }
    float position();
    void setMuted(bool muted);
private:
    SDL_AudioStream* mStream=nullptr;
    std::vector<unsigned char> mPCM;
    double mBytesPerSecond=0;
    float mDuration=0, mPosition=0;
    bool mInitialized=false, mRunning=false, mMuted=false;
};
