#pragma once
#include <string>
#include <vector>
#include <array>
#include "systems/MeteorImpact.h"
struct SDL_AudioStream;

// SDL audio owns the playback clock; decoded PCM is generated by the build.
class MusicPlayer {
public:
    MusicPlayer() = default;
    MusicPlayer(const MusicPlayer&) = delete;
    MusicPlayer& operator=(const MusicPlayer&) = delete;
    ~MusicPlayer();
    bool load(const std::string& wavPath);
    bool restart();
    bool seek(float seconds);
    void setPaused(bool paused);
    bool setPlaybackRate(float rate);
    bool loadImpact(const std::string& wavPath);
    void playImpacts(const std::vector<MeteorImpact>& impacts,const glm::vec3& listener,float time);
    unsigned impactPlayCount() const { return mImpactPlayCount; }
    void release();
    bool ready() const { return mStream!=nullptr; }
    bool running() const { return mRunning; }
    float duration() const { return mDuration; }
    float position();
    void setMuted(bool muted);
private:
    struct Voice { SDL_AudioStream* stream=nullptr; float gain=0; };
    std::array<Voice,4> mVoices{};
    std::vector<unsigned char> mImpactPCM;
    float mLastImpactTime=-1;
    unsigned mNextVoice=0, mImpactPlayCount=0;
    unsigned mDevice=0;
    SDL_AudioStream* mStream=nullptr;
    std::vector<unsigned char> mPCM;
    double mBytesPerSecond=0;
    unsigned mBytesPerFrame=0;
    float mRate=1;
    bool mPaused=false;
    float mDuration=0, mPosition=0;
    bool mInitialized=false, mRunning=false, mMuted=false;
};
